server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: event-service
          uri: http://event-service:8080
          predicates:
            - Path=/api/**

jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharactersLongForJWT
