spring.application.name=event-service
server.port=8082

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ticketrush}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:minh}
spring.datasource.password=${DB_PASSWORD:minh123}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.seat-lock.release.enabled=true
app.seat-lock.release.delay-ms=60000
app.seed.enabled=true
